[build.processing.css]
minify = true
bundle = false

[build.processing.js]
minify = true
bundle = false

[[plugins]]
package = "netlify-plugin-minify-html"

  [plugins.inputs]
    contexts = [
      'production',
      'branch-deploy',
      'deploy-preview'
    ]
